#!/bin/bash

#SBATCH --job-name=pesticides_pipeline_appt
#SBATCH --output=pesticides_pipeline_appt.log
#SBATCH --error=pesticides_pipeline_appt.error
#SBATCH --mail-user=messierkp@nih.gov
#SBATCH --mail-type=END,FAIL
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=32
#SBATCH --mem=256g
#SBATCH --partition=geo

# assign assets properly -- double check SBATCH command
# Asset assignment requires cgroups v2 functionality.
# Users should consult the IT department on this to explicitly set
# asset assignment arguments including --cpus, --memory, and --memory-reservation.
# apptainer exec --mount type=bind,src=/ddn/gs1/group/set/Projects/PrestoGP_Pesticides/input,dst=/pipeline/input --mount type=bind,src=/ddn/gs1/group/set/pipeline/Pesticides_container,dst=/opt/_targets --mount type=bind,src=/ddn/gs1/home/songi2/projects/targets_PrestoGP,dst=/mnt --no-mount bind-paths --memory 768G --memory-reservation 640G --cpus 64 --writable-tmpfs /ddn/gs1/group/set/pipeline/pipeline_image.sif Rscript /tar_run.R

# For details about apptainer commands,
# apptainer --help
# apptainer exec --help
# Below is generated by Copilot.
# This script executes a command using the "apptainer" tool. It mounts several directories and runs an R script.

# NOTE: the paths were modified for ISong testing
apptainer exec \
  --mount type=bind,src=/ddn/gs1/group/set/Projects/PrestoGP_Pesticides/input,dst=/pipeline/input \
  --mount type=bind,src=/ddn/gs1/group/set/pipeline/Pesticides_container,dst=/opt/_targets \
  --mount type=bind,src=/ddn/gs1/home/messierkp/group_prj_local/targets_PrestoGP,dst=/mnt \
  --no-mount bind-paths \
  --writable-tmpfs \
  /ddn/gs1/group/set/pipeline/pipeline_image_is.sif \
  Rscript /mnt/run.R

# The "apptainer exec" command is used to execute a command within a container. It provides options to mount directories and specify the command to run.

# The "--mount" option is used to mount directories inside the container. In this script, three directories are mounted:
# - "/ddn/gs1/group/set/Projects/PrestoGP_Pesticides/input" is mounted to "/pipeline/input"
# - "/ddn/gs1/group/set/pipeline/Pesticides_container" is mounted to "/opt/_targets"
# - "/ddn/gs1/home/songi2/projects/targets_PrestoGP" is mounted to "/mnt"

# The "--no-mount bind-paths" option is used to prevent the container from mounting any additional directories.

# The "--writable-tmpfs" option is used to create a writable temporary file system inside the container.

# The "/ddn/gs1/group/set/pipeline/pipeline_image.sif" is the path to the container image that will be used.

# The "Rscript /mnt/run.R" command is the command that will be executed inside the container. It runs an R script located at "/mnt/run.R".
