---
title: "03_Create_HUC_Spatial_Join"
author: "Kyle P Messier"
date: "2023-05-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(tidyverse)
library(data.table)
library(sf)

AZO.points <- sf::st_read("input/data_process/data_AZO_file.shp")

HUC12 <- st_read("input/WBD-National/WBD_National_GDB.gdb", layer = "WBDHU12")

# Convert both the AZO points and HUC to Albers Equal Area projected coordinate system
AZO.t <- st_transform(AZO.points, "+proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=23 +lon_0=-96 +x_0=0 +y_0=0
+ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs")

huc.t <- st_transform(HUC12, "+proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=23 +lon_0=-96 +x_0=0 +y_0=0
+ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs")

AZO.HUC.join <- sf::st_join(AZO.t, huc.t)

AZO.HUC.join$huc10 <- str_sub(AZO.HUC.join$huc12, 1, 10)
AZO.HUC.join$huc08 <- str_sub(AZO.HUC.join$huc12, 1, 8)
AZO.HUC.join$huc06 <- str_sub(AZO.HUC.join$huc12, 1, 6)
AZO.HUC.join$huc04 <- str_sub(AZO.HUC.join$huc12, 1, 4)
AZO.HUC.join$huc02 <- str_sub(AZO.HUC.join$huc12, 1, 2)

sf::st_write(AZO.HUC.join, "input/data_process/data_AZO_watershed_huc_join.shp")
```

